# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_loadings <- function(n, p_m, Ktot, X_m, facTfac, fac, mu_m, s2_inv_m, prec_m) {
    .Call(`_jafar_update_loadings`, n, p_m, Ktot, X_m, facTfac, fac, mu_m, s2_inv_m, prec_m)
}

update_loadings_parallel <- function(n, p_m, Ktot, X_m, facTfac, fac, mu_m, s2_inv_m, prec_m) {
    .Call(`_jafar_update_loadings_parallel`, n, p_m, Ktot, X_m, facTfac, fac, mu_m, s2_inv_m, prec_m)
}

msf <- function(lambda, pivot) {
    .Call(`_jafar_msf`, lambda, pivot)
}

msfOUT <- function(lambda, pivot) {
    .Call(`_jafar_msfOUT`, lambda, pivot)
}

aplr <- function(matr, perm) {
    .Call(`_jafar_aplr`, matr, perm)
}

